ДЗ 1
artiebears13/2024-2-VK-EDU-Frontend-A-Medvedev pull request #1
Opened 2024-09-18 08:57 UTC by artiebears13

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его

Что было сделано:
- написаны функции в файла  `convertBytesToHuman.js`, `correctSentence.js`, `nonUniqueElements.js`
- написаны тесты `convertBytesToHuman.test.js`
*

2024-09-21 12:12 UTC, Ivan-Bir requested changes

2024-09-21 12:12 UTC, Ivan-Bir commented on correctSentence.test.js
> +  expect(correctSentence("greetings, friends")).toBe("Greetings, friends.")
Нет тестов на пограничные случаи. Например обработка пустой строки

2024-09-21 12:12 UTC, Ivan-Bir commented on nonUniqueElements.test.js
> +  expect(nonUniqueElements([10, 9, 10, 10, 9, 8])).toEqual([10, 9, 10, 10, 9]);
Добавил бы парочку тесткейсов от себя

2024-09-23 15:01 UTC, artiebears13 commented on convertBytesToHuman.js
> +    *     10.005*100 -> 1000.5000000000001
В задании которое в файле `convertBytesToHuman.js` есть пример
`convertBytesToHuman(123123123) === '117.42 MB';`
поэтому сделал так

2024-09-24 14:01 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +    *     10.005*100 -> 1000.5000000000001
Мегабайт может быть не целым, а вот байт, как я понимаю, нет

2024-09-24 14:08 UTC, Ivan-Bir approved these changes

2024-09-24 14:11 UTC, Ivan-Bir commented
Окей, ставлю апрув
Однако, вопрос с нецелыми байтами оставляю на рассмотрение с преподавателями, поскольку он явно не прописан в условии
Если поправишь, как я указал, до дедлайна первого дз, то тебе будет плюсик в карму

2024-09-25 20:40 UTC, martinkomitsky commented on pull_request_template.md
> +Прошу @martinkomitsky, @haseprogram, @kgrechin или @ваш_назначенный_ментор проверить его.
@ваш_назначенный_ментор надо заменить на твоего назначенного ментора

2024-09-25 20:42 UTC, martinkomitsky commented on pull_request_template.md
> +Прошу @martinkomitsky, @haseprogram, @kgrechin или @ваш_назначенный_ментор проверить его.
```suggestion
Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.
```

2024-09-25 20:43 UTC, martinkomitsky commented on pull_request_template.md
> +Прошу @martinkomitsky, @haseprogram, @kgrechin или @ваш_назначенный_ментор проверить его.
чтобы не терять время, в первый раз сделаю это сам. А далее нужно всегда быть внимательным!

2024-09-25 20:43 UTC, martinkomitsky approved these changes
12!

2024-09-25 20:43 UTC, merged