Hw10
artiebears13/2024-2-VK-EDU-Frontend-A-Medvedev pull request #10
Opened 2024-12-20 07:35 UTC by artiebears13

# Домашнее задание №10

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:
* Добавлена информация об онлайне пользователя
* Добавлена информация о чате
* Страница пользователей

# Деплой
* Пока дз9 в деплое

2024-12-21 14:07 UTC, Ivan-Bir commented
Давай реализуем удаление сообщения в этом дз. И добавь пж ховер на кнопку авторизации

2024-12-21 14:08 UTC, Ivan-Bir commented
Давай реализуем удаление и редактирование сообщения в этом дз. И добавь пж ховер на кнопку авторизации

2024-12-23 18:45 UTC, martinkomitsky commented
можно фиксить

2025-01-05 17:23 UTC, artiebears13 commented
Сделал удаление сообщений, по поводу редактирования, там барахлит апи, мне сказали, что уже не будут фиксить

2025-01-10 13:19 UTC, martinkomitsky commented
@Ivan-Bir

2025-01-12 22:36 UTC, Ivan-Bir requested changes
Контекстное меню с удалением сильно вверх уехало, попробуй рендерить его непосредственно над сообщением, либо под мышкой
![изображение](https://github.com/user-attachments/assets/df0f2fcf-1fad-49fc-abd3-c5635fae5b5e)

И сейчас появился баг с профилями пользователей, при клике на чужой профиль кидает на мой с ошибкой
![изображение](https://github.com/user-attachments/assets/c84bea94-7bb8-497c-9534-87dad433e81c)

Поправишь это?

2025-01-13 09:45 UTC, artiebears13 commented
Поправил

2025-01-13 19:05 UTC, Ivan-Bir submitted a review, later dismissed

2025-01-14 20:35 UTC, Ivan-Bir approved these changes

2025-01-15 15:00 UTC, merged

2025-01-15 15:00 UTC, martinkomitsky commented
7