Hw13
artiebears13/2024-2-VK-EDU-Frontend-A-Medvedev pull request #11
Opened 2024-12-23 14:12 UTC by artiebears13

# Домашнее задание №13

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:
* Добавлена утилита перевода на TS
*
*

2025-01-19 11:37 UTC, Ivan-Bir requested changes

2025-01-19 11:37 UTC, Ivan-Bir commented on react-chat/src/ts/utils/class.ts
> +    private readonly _base_url: string = 'https://api.mymemory.translated.net/get?q=';
Лучше не привязываться к структуре ссылки. Т.е. параметр q лучше добавлять в соответствующем методе формирования итогового url

2025-01-19 11:37 UTC, Ivan-Bir commented on react-chat/src/ts/utils/class.ts
> +        if (!responseData.responseData.translatedText){
безопасней проверить и вложенные объекты, потому что они потенциально undefined
!responseData?.responseData?.translatedText

2025-01-19 11:37 UTC, Ivan-Bir commented on react-chat/src/ts/utils/interface.ts
> +export interface ICacheResponse {
Этот интерфейс дублирует ITranslationResult. Можно, например, создавать базовый для обоих интерфейс и отнаследоваться от него

2025-01-19 11:37 UTC, Ivan-Bir commented on react-chat/src/ts/utils/testTranslate.ts
> +        await fetchTranslation(testData).then(res=> console.log(res));
Это не совсем похоже на тест. Здесь нет проверки как таковой, просто вывод в консоль юзеру.
Можно как сделать: Если перевод требуется на англ, то проверить в ответе, что есть английские символы (на русский, то русские символы в ответе. Это потому что интеграционный тест не должен проверять чужой сервис, поведение которого строго не регламентировано). Если ответ из кэша, то проверить, что модуль fetchTranslation вернул usedCache: true и в случае ошибки писать в console.error (но в реальном продакшене вместо этого шлются события на сервер аналитики, где считается процент таких проблемных пользователей)

Либо переделать этот тест в юнит с моком ответа от апи. Всё зависит от того, что именно ты тестируешь здесь

2025-01-20 10:05 UTC, artiebears13 commented
Поправил

2025-01-22 13:27 UTC, Ivan-Bir approved these changes, later dismissed

2025-01-22 13:27 UTC, Ivan-Bir commented on react-chat/src/ts/utils/class.ts
> +    private readonly _base_url: string = 'https://api.mymemory.translated.net/get?';
Вопросик на конце лишний

2025-01-22 13:27 UTC, Ivan-Bir commented on react-chat/src/ts/utils/interface.ts
> +export interface ICacheResponse extends IBaseTranslationResponse {}
Ну ещё как вариант валидна такая запись
export type ICacheResponse = IBaseTranslationResponse;

2025-01-22 13:30 UTC, Ivan-Bir commented
Апрув

2025-01-22 13:46 UTC, martinkomitsky commented
@artiebears13 фикс конфликты и смержу

2025-01-22 14:16 UTC, artiebears13 commented
Исправил, добавил моки апи в тесты кэширования и оставил оригинальное обращение в интеграционном тесте

2025-01-22 14:34 UTC, Ivan-Bir submitted a review, later dismissed
Четко 👍

2025-01-22 18:54 UTC, martinkomitsky commented
![image](https://github.com/user-attachments/assets/f564ca9b-ec98-4be0-8292-292f8fe0b5d2)
не совсем @artiebears13 (

2025-01-22 21:40 UTC, artiebears13 commented
Поправил

2025-01-23 08:06 UTC, martinkomitsky approved these changes

2025-01-23 08:12 UTC, merged

2025-01-23 08:12 UTC, martinkomitsky commented
7

2025-01-23 08:12 UTC, martinkomitsky commented
поздравляю с последней домашкой!