ДЗ2
artiebears13/2024-2-VK-EDU-Frontend-A-Medvedev pull request #2
Opened 2024-09-30 15:00 UTC by artiebears13

# Домашнее задание №2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:
* Сделана верстка мессенжера
* Написан `index.js` для работы с сообщениями и localStorage

**Деплой**: https://artiebears13.github.io/2024-2-VK-EDU-Frontend-A-Medvedev/

2024-09-30 20:03 UTC, Ivan-Bir commented
Привет!
Джоба сфейлилась, нет деплоя

2024-09-30 20:35 UTC, Ivan-Bir requested changes
Поправить метод хранения сообщений и починить деплой и будет четко

2024-09-30 20:35 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +}
Неоптимально по ресурсам. На каждое добавление ты парсишь все сообщения, и потом обратно всё это в json. 95% данных конвертируются туда-сюда без надобности. Пожалей пользователей со слабыми телефонами: они или умрут от ожидания отправки сообщения, или сожгут себе руки из-за перегрева проца.
Давай придумаем какой-то ещё способ хранения сообщений

2024-09-30 20:35 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +    messageItem.innerHTML = `${message.text} <span class="time">${message.time}</span>`;
Понимаю твой соблазн писать как в реакте html вперемешку с js. Но innerHTML - это зло в чистом виде. Это источник уязвимостей XSS и вектор атаки для вредителей, если интересно могу дать что-то почитать.
Вместо него придумали более безопасный способ вставки содержимого на страницу. Посмотри тут https://developer.mozilla.org/ru/docs/Web/API/Element/insertAdjacentHTML

2024-09-30 20:35 UTC, Ivan-Bir commented on simple-chat/src/index.css
> +.receiver-photo > img{
Лучше вместо сложных селекторов использовать отдельные классы с понятными именами

2024-09-30 20:35 UTC, Ivan-Bir commented on simple-chat/src/index.css
> +ul {
Стилизовать стандартные теги не очень вариант. А что если где-то в другом месте тебе понадобится ul другого вида? Для элементов удобнее и практичнее использовать классы
Но стили для тегов тоже пишут, например когда нужно сбросить стандартные стили браузера, например на теге body, или a

2024-09-30 20:35 UTC, Ivan-Bir commented on simple-chat/src/index.css
> +    border-bottom-left-radius: 0.8rem 0.7rem;
Зачем понадобились дробные rem?
Удобнее как по мне использовать px да и голову не морочить

2024-09-30 20:35 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +    event.preventDefault();
Расскажешь, зачем так пишут?

2024-10-01 16:22 UTC, artiebears13 commented on simple-chat/src/index.js
> +    event.preventDefault();
Так пишут чтобы отключить дефолтное поведение

2024-10-01 16:27 UTC, artiebears13 commented on simple-chat/src/index.js
> +}
Поменял, теперь сообщения сохраняются каждое в свое поле, так же есть переменная `lastMessageId` которая указывает на номер последнего сообщения. Ключи в localStorage это `message_${<номер>}`

2024-10-01 20:04 UTC, Ivan-Bir commented on simple-chat/src/index.js
> +    event.preventDefault();
Опиши плиз подробней. Какое дефолтное поведение? Почему вызывается на объекте события?

2024-10-01 20:27 UTC, Ivan-Bir approved these changes

2024-10-01 21:08 UTC, HaseProgram approved these changes
12!

2024-10-01 21:12 UTC, merged