ДЗ4
artiebears13/2024-2-VK-EDU-Frontend-A-Medvedev pull request #4
Opened 2024-10-13 20:30 UTC by artiebears13

# Домашнее задание №4

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:
* Переписано на SPA
* Реализован поиск по сообщениям (сообщение и имя человека) 
* Переписал на SCSS
* Добавлены переменные
* Добавлено меню по кнопке "бергер"
* Смена темы (в меню)
* Добавлены плавные анимации

### Деплой: 
https://artiebears13.github.io/2024-2-VK-EDU-Frontend-A-Medvedev/

2024-10-14 19:52 UTC, Ivan-Bir requested changes
Хороший прогресс в продуктовом плане! Супер респект за смену темы

Есть некоторые моменты, которые можно поправить для продукта:
Неработающие кнопки задизейблить, чтобы не путали.
Бордеры между чатами слишком заметные, можно помягче, или вовсе убрать (в обоих темах)
Шрифт можно поискать тоже не такой резкий
Съехала иконка плюсика на добавлении
Есть некоторая дерганность в интерфейсе, думаю связано с тем, что все элементы создаешь через document.createElement и вставляешь их по очереди. Если уменьшить число вставок и взаимодействий с DOM, то это повысит плавность. Это в принципе решится, когда перейдем на реакт, но и сейчас усвоить принципы отзывчивого интерфейса не будет лишним

2024-10-15 16:43 UTC, artiebears13 commented on simple-chat/src/mocks/__mocks__.js
> +        photo: 'https://picsum.photos/50/50?random=3',
Я так понимаю они теперь только с впн грузятся, странно конечно что забанили плейсхолдер)

2024-10-15 16:44 UTC, artiebears13 commented on simple-chat/src/mocks/__mocks__.js
> +        photo: 'https://picsum.photos/50/50?random=3',
но теперь можно свою локальную фотку на новый чат поставить

2024-10-17 10:12 UTC, artiebears13 commented
Сейчас заметил что кнопка опять поплыла, чуть позже исправлю

2024-10-17 16:12 UTC, Ivan-Bir commented on simple-chat/src/components/chatList/header/chatListHeader.js
> +    // Добавляем классы анимации и обработчик события
Давай договоримся закрывать коменты, которые фиксишь как написано, если меняешь по-своему или вовсе нет, то отвечай в треде. Сейчас это проигнорено

2024-10-17 16:30 UTC, Ivan-Bir approved these changes
В целом хорошо. Замечания можно поправить уже в след дз, но не игнорировать)
Есть небольшие баги с отображением непрочитанных, но не крит. Посмотри повнимательнее что там

2024-10-17 16:30 UTC, Ivan-Bir commented on simple-chat/src/components/chatList/menu/Menu.js
> +    );
Если оставляешь незадизейбленными, то ждем в следующем дз эти функции)

2024-10-17 16:30 UTC, Ivan-Bir commented on simple-chat/src/components/chatWindow/chatWindowView.js
> +    const fragment = document.createDocumentFragment();
👍👍👍

2024-10-17 16:30 UTC, Ivan-Bir commented on simple-chat/src/components/modal/modal.js
> +            }
Супер, что не забываешь про граничные случаи. Но alert и ему подобные - это зло. Такие вызовы блокируют взаимодействие со страницей. Здесь можно обойтись ошибкой на форме
Можно ещё добавить обработку случая для поиска, когда не нашлось чатов

2024-10-17 16:30 UTC, Ivan-Bir commented on simple-chat/src/components/chatList/createChatButton/createChatButton.js
>      chatButton.classList.add('create-chat-button');
Не хватает контейнера для иконки. А там внутри уже можно флексами центрировать

2024-10-19 12:24 UTC, merged

2024-10-19 12:24 UTC, martinkomitsky commented
12!