Hw5
artiebears13/2024-2-VK-EDU-Frontend-A-Medvedev pull request #5
Opened 2024-10-24 10:34 UTC by artiebears13

# Домашнее задание №5

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:
* Переписал на реакт
* Поправил значки чтения сообщений
* Найденное сообщение теперь мигает выделение
* Созданы контексты
* Некоторые обращения в localStorage сделал асинхронными для симуляции бэкенда

Разобрался с проблемой деплоя. Оказывается что неправильно настроил роутинг, но зато получил отличный урок))

2024-10-27 12:09 UTC, Ivan-Bir requested changes
В целом переезд выполнен хорошо, нужно поправить некоторые моменты в UI.
Дополню несколькими моментами:
1. Модалку хотелось бы закрывать нажатием на внешнюю область
2. Было бы классно добавить селектор с эмодзи
3. А как насчет научить приложение отправлять картинки?
Перезагрузку страницы можно поправить в следующем дз

2024-10-27 12:09 UTC, Ivan-Bir commented on react-chat/src/components/chatList/headerComponents/SearchBar/SearchBar.jsx
> +                    placeholder="Search..."
Этот текст плохо видно + он на англе, хотя остальные элементы на русском

2024-10-27 14:32 UTC, artiebears13 commented on react-chat/src/components/AlertMessage/AlertMessage.jsx
> +export const AlertMessage = () => {
сделал сокрытие и перевел все на русский, по поводу налезания в моем понимании так норм потому что модал с ошибкой самый приоритетный и должен приковывать внимание пользователя

2024-10-27 14:39 UTC, artiebears13 commented on react-chat/src/components/chatList/headerComponents/Title/Title.jsx
> +export const Title = ({text}) => {
я уже в следующем дз переиспользовал его)

2024-10-27 14:58 UTC, artiebears13 commented on react-chat/src/pages/PageChat/PageChat.jsx
> +export const PageChat = () => {
Вроде пофиксил, но такое ощущение как будто у меня еще браузер что то кэширует потому что странно мигало.
Например у меня мигала вся страницпаа, потом обновил, мигают только сообщения, потом опять обновил, мигает вся страница и тд...

2024-10-27 14:58 UTC, artiebears13 commented on react-chat/src/pages/PageChat/PageChat.jsx
> +export const PageChat = () => {
Но вообще супер крутой инструмент, спасибо!

2024-10-27 16:08 UTC, artiebears13 commented
-  Пофиксил, касательно инструмента отрисовки так и не смог победить его, но сделал по логике как мог представить. 
 - Касательно картинок в сообщениях тоже думал, но могу пообещать что сделаю в следующем дз, тк я его параллельно уже делаю и проще так будет, чтобы это поскорее сдать и сосредоточиться на новом, аналогично по селектору эмодзи, но его лучше распределить и сделать через дз)

p.s
Просто морально тяжело делать 2 домашки параллельно)

2024-10-28 07:59 UTC, artiebears13 commented
Заметил что последний коммит не запушил, теперь всё)

2024-10-30 10:30 UTC, Ivan-Bir approved these changes

2024-10-31 06:29 UTC, HaseProgram approved these changes
Отлично, 12!

2024-10-31 06:29 UTC, merged