ДЗ6
artiebears13/2024-2-VK-EDU-Frontend-A-Medvedev pull request #6
Opened 2024-10-31 08:12 UTC by artiebears13

# Домашнее задание №6

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:
* Роутинг (HashRouter)
* Страница "Профиль" по клику на юзера в меню
![image](https://github.com/user-attachments/assets/bee9b5f1-831c-4148-b78b-2b434b636b60)

* Возможность редактировать данные пользователя (значок карандаша на странице пользователя)
* Добавлена возможность отправлять картинки в чате

**Деплой:**
https://artiebears13.github.io/2024-2-VK-EDU-Frontend-A-Medvedev/

2024-11-02 15:27 UTC, Ivan-Bir requested changes
Есть замечания по коду, которые нужно поправить.

Дополню ещё моментами по UI:
1) Хотелось бы иметь возможность менять аватарки уже имеющимся контактам. Логика уже есть, осталось её заиспользовать в другом месте
2) Когда грузим фотку, появляются большие отступы по бокам
3) Нельзя по-прежнему закрыть попап кликом на внешнюю область

2024-11-02 15:27 UTC, Ivan-Bir commented on react-chat/src/components/EditableFields/ProfilePhoto/ProfilePhoto.jsx
> +    const [photoPreview, setPhotoPreview] = useState(selfPerson.photo || 'https://avatar.iran.liara.run/public');
Здесь почему-то не приходит url фотки, поэтому в интерфейсе всегда дефолтное значение, хотя в localStorage она есть. Хотя в боковой менюшке грузится норм

2024-11-02 15:27 UTC, Ivan-Bir commented on react-chat/src/components/Menu/Menu.jsx
> +                <div className="user-data" onClick={toProfile}>
Предлагаю навесить какой-то ховер, чтобы было заметнее, что профиль можно редактировать

2024-11-02 15:27 UTC, Ivan-Bir commented on react-chat/src/components/MessageItem/MessageItem.jsx
> +    console.log('image', message.image)
Лучше не деплоить отладочный код на прод. Здесь и далее

2024-11-02 15:27 UTC, Ivan-Bir commented on react-chat/src/components/Headers/ProfileHeader/ProfileHeader.jsx
> +                    <EditIcon className={"white"}>arrow_edit</EditIcon>
Не сразу даже заметил эту иконку для возможности редактирования. Понятнее для пользователей вынести её где-то на форме. Шапка относится к верхнеуровневым дейтсвиям

2024-11-02 15:27 UTC, Ivan-Bir commented on react-chat/src/components/Inputs/MessageInput/MessageInput.jsx
> +                            onClick={() => attachedImageInputRef.current.click()}
Имей ввиду, что на каждый ререндер твоих компонентов все такие функции создаются заново.
Здесь можно просто  onClick={attachedImageInputRef.current.click}

2024-11-05 09:12 UTC, artiebears13 commented on react-chat/src/components/EditableFields/ProfilePhoto/ProfilePhoto.jsx
> +    const [photoPreview, setPhotoPreview] = useState(selfPerson.photo || 'https://avatar.iran.liara.run/public');
Нашел ошибку, я не так перезаписывал их в контекст

2024-11-05 09:55 UTC, artiebears13 commented on react-chat/src/components/Inputs/MessageInput/MessageInput.jsx
> +                            onClick={() => attachedImageInputRef.current.click()}
Попробовал так сделать, но тут ошибка вылетает, насколько понял, связано с тем что при первом рендере реф еще пустой

2024-11-05 14:26 UTC, artiebears13 commented on react-chat/src/components/EditableFields/ProfileAbout/ProfileAbout.jsx
> +                <p className="profile-page-key"> О себе: </p>
Есть)

2024-11-05 14:31 UTC, artiebears13 commented
Внес исправления:

- перенес на модули проект
- добавил возможность менять аватарки уже имеющимся контактам (в чате с человеком надо кликнуть на его имя или аватарку)
- добавил закрытие поп апа на внешнюю область

2024-11-10 09:57 UTC, Ivan-Bir approved these changes

2024-11-10 09:57 UTC, Ivan-Bir commented
Апрув

2024-11-10 10:17 UTC, Ivan-Bir commented
Также заметил, что если грузим картинку больше 3мб, то приложение умирает. Давай обработаем этот кейс и выведем сообщение юзеру что пошло не так

2024-11-10 11:05 UTC, merged

2024-11-10 11:06 UTC, martinkomitsky commented
12!