Hw7
artiebears13/2024-2-VK-EDU-Frontend-A-Medvedev pull request #7
Opened 2024-11-15 15:21 UTC by artiebears13

# Домашнее задание №7

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:
* Привязан бэк
* Получаю сообщения по центрифуге

Дополнительно прикладываю скринкаст
![](https://github.com/artiebears13/2024-2-VK-EDU-Frontend-A-Medvedev/blob/hw7/screencasts/vk_screencast.gif)

На скринкасте показаны:
- Регистрация
- Логин
- Возможность создавать личный чат, в окне создания - список пользователей с возможностью поиска по имени/никнейму, вначале он пустой тк нет еще пользователей
- Как только регистрием еще одного юзера, список уже будет не пустой
- При клике на пользователя, открывается чат с ним
- Как только пишем сообщение, оно приходит другому
- Есть возможность отправлять картинки
- Есть возможность редактировать описание профиля и аватарки
- Есть возможность создавать групповые чаты на несколько человек
- Открытается также модалка создания чата и там аналогично выбираем пользователей, выбранные пользователи темнее
- При клике юзер добавляется, при повторном -- убирается
- Тут же показал возможность поиска по имени
- Строка поиска сверху на главной выполняет поиск по названию групповых чатов, как в апи

## Деплой:
https://artiebears13.github.io/2024-2-VK-EDU-Frontend-A-Medvedev/

2024-11-22 11:22 UTC, Ivan-Bir requested changes
В целом гуд
1) Почему после регистрации не открываем сразу список чатов? Мне, как юзеру, очень лень ещё раз вводить логин + пароль
2) Ломается приложение при попытке посмотреть информацию о пользователе
![Снимок экрана 2024-11-22 в 14 20 54](https://github.com/user-attachments/assets/f4d856ab-a78e-4f3c-9dc4-9e27cfec4f3c)
3) Нет возможности выйти из приложения

2024-11-22 11:22 UTC, Ivan-Bir commented on react-chat/src/pages/PageChat/PageChat.jsx
> +    }, [chatId]);
пустой callback

2024-11-22 11:22 UTC, Ivan-Bir commented on screencasts/vk_screencast.gif
Достаточно в МР приложить, в репе лучше не хранить такие вещи

2024-11-23 10:58 UTC, artiebears13 commented
- Добавил кнопку "выход" в профиль 
- Добавил автологин после успешной регистрации

скринкаст почему-то не превьюится, поэтому оставлю тут ссылку на него
https://artiebears.com/vk_screencast.gif

2024-11-24 15:06 UTC, Ivan-Bir commented
![изображение](https://github.com/user-attachments/assets/45656e21-87eb-460c-8831-e5c974636781)
Ещё забыл про этот момент. Юзер только зарегался, а ему уже грустить говорят. Непонятно, что сделать, чтобы было хорошо. Можно сразу заходить, что, чувак, скорее создавай чат и начинай общаться!

2024-11-24 15:39 UTC, artiebears13 commented
Поправил текст и сделал мигающую кнопку чтобы привлечь пользователя.
По идее теперь не должен грустить)

2024-11-25 11:42 UTC, Ivan-Bir approved these changes

2024-11-25 11:47 UTC, Ivan-Bir commented
Чтобы не дудосить апишку на каждый новый символ в поиске используют разные подходы. Почитай про декораторы debounce и throttle. И давай поправим это в следующем дз
https://learn.javascript.ru/call-apply-decorators#dekorator-debounce
https://learn.javascript.ru/call-apply-decorators#tormozyaschiy-throttling-dekorator

2024-11-26 22:04 UTC, HaseProgram commented
Супер! 10

2024-11-26 22:04 UTC, merged