ДЗ8
artiebears13/2024-2-VK-EDU-Frontend-A-Medvedev pull request #8
Opened 2024-12-03 12:26 UTC by artiebears13

# Домашнее задание №8

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:
* Добавлена возможность делиться геопозицией
* Добавлена возможность отправлять голосовые сообщения
* При новом сообщении появляется уведомление или оно автоматически становится прочитанным, если открыт этот же чат
* Сообщения читаются
* Добавил debounce на поиск по чатам

## Деплой:
https://artiebears13.github.io/2024-2-VK-EDU-Frontend-A-Medvedev/#/

2024-12-08 13:50 UTC, Ivan-Bir requested changes
Привет! По коду докапываться уже смысла не вижу, явных косяков не увидел

По UI ещё есть огрехи:
* Не видно дату, если сообщение прошлого дня. Хотя бы пометки "сегодня", "вчера", "ранее", чтобы слишком не душиться, а будет время - доведешь до ума
* Если создать чат, ничего не написать и выйти, то больше попасть в этот диалог возможности нет
* Не хватает опции отменить голосовое
* Если не указать название группового чата, то высвечивается общая ошибка, хотя на это просто указать и апишку дергать не придется

Желательное:
* Ошибка в консоли на каждое сообщение
![изображение](https://github.com/user-attachments/assets/2950d734-8c41-4c52-a145-149d11439aff)
* Не получилось посмотреть как работает отправка геолокации из Firefox - всё время пишет ошибку (которая не переведена кстати)

2024-12-08 16:36 UTC, artiebears13 commented
По замечаниям поправил, 
- добавил дату сообщения в формате "сегодня, вчера, дата"
- сделал чтобы пустые чаты виднелись в списке чатов, там будет текст "нет сообщений"
- отмена гс добавлена
- и исправлен текст ошибки на отсутствие названия чата
- по поводу ошибки в консоли на каждое сообщение и ошибки геолокации, не смог отловить, прикрепляю гиф
![Новый проект](https://github.com/user-attachments/assets/5ed172c4-e807-4284-b15e-9821b55fc059)

так же, openstreetmap сейчас работает с впн, но если пользоваться без впн, там просто будет пустой iframe (как предпоследнее сообщение в левом окне)

2024-12-15 17:50 UTC, Ivan-Bir commented
Ошибки в консоли были в Firefox'е, сейчас не вижу.
Странно, что фотка чата VK Образования не прогружается, хотя в ответе она есть, и при переходе в чат, отображается в хедере. И в целом, если из api аватар приходит со значением null, то давай показывать заглушку.

2024-12-17 08:16 UTC, artiebears13 commented
Исправил

2024-12-17 09:05 UTC, Ivan-Bir approved these changes

2024-12-17 10:26 UTC, merged